# Dockerfile


FROM ruby:3.1.1

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

WORKDIR /myapp

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

RUN bundle install

COPY . /myapp

RUN bundle exec rake assets:precompile

# Expose port 3000 to the Docker host, so we can access the app
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
